version: 2

project_name: factorio-mod-updater

builds:
  - main: .
    binary: mod_updater
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

changelog:
  sort: asc

release:
  github:
    owner: dreamdenizen
    name: factorio-mod-updater
